name: myproject
version: 1.0.0
dependencies:
  - package: compose-example
    source:
      type: git
      url: https://github.com/iignatevich/compose-example.git
      # ref: branch-name
      # tag: tag-name
