name: Commit Workflow

on:
  push:
  workflow_dispatch:

jobs:
  no-tty-in-ci:
    name: Ensure no TTY if user does not need to input anything
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          echo
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          ./bin/launchr login --url=http://***.git --username="***" --password="***" --keyring-passphrase="***"

  command-ok:
    name: Ensure main command brought by plugin does not fail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          echo
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          ./bin/launchr login --url=https://github.com/launchrctl/launchr.git

  go-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          echo
          date
          pwd
          whoami
          make lint

  go-tests:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          echo
          date
          pwd
          whoami
          make test

